apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-dummy-postgres-deployment
spec:
  serviceName: "postgres"
  selector:
    matchLabels:
      app:  app-dummy-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: app-dummy-postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim