apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-dummy-redis-deployment
spec:
  serviceName: "redis"
  selector:
    matchLabels:
      app: app-dummy-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: app-dummy-redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis:alpine        
        volumeMounts:
          - name: redis-data
            mountPath: /data
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 6379
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pv-volume-claim
