kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv-volume
  labels:
    app: appd-dummy-redis-storage
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pv-volume-claim
  labels:
    app: appd-dummy-redis-storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi