apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dummy-redis-deployment
spec:
  selector:
    matchLabels:
      app: app-dummy-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: app-dummy-redis
    spec:
      containers:
      - name: redis
        image: redis:alpine        
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
