apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dummy
spec:
  selector:
    matchLabels:
      app: app-dummy
  replicas: 1
  template:
    metadata:
      labels:
        app: app-dummy
    spec:
      containers:
      - name: webapp
        imagePullPolicy: Never
        env: 
        - name: APP_MODE
          value: "api"          
        image: camilortte/djangotestkubernetes:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
