apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dummy-web
spec:
  selector:
    matchLabels:
      app: app-dummy-web
  replicas: 1
  template:
    metadata:
      labels:
        app: app-dummy-web
    spec:
      containers:
      - name: webapp
        env: 
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: app-dummy-config-map
              key: WEB_APP_MODE
        - name: REDIS_HOST
          value: redis-host
        image: camilortte/djangotestkubernetes:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
